import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, Globe2, Lightbulb, Quote, Users } from "lucide-react";
import hero from "@/assets/campus-hero.jpg";
import studio from "@/assets/learning-studio.jpg";
import { programs, faculty, stories } from "@/lib/content";
import { AdmissionsBand, ProgramCard, SectionHeading } from "@/components/shared";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Northstar Institute — Learn with purpose" }, { name: "description", content: "Career-focused undergraduate, postgraduate, diploma, and professional programmes." }, { property: "og:title", content: "Northstar Institute — Learn with purpose" }, { property: "og:description", content: "Career-focused higher education for a changing world." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Home });

function Home() { return <>
  <section className="relative min-h-[680px] overflow-hidden bg-primary"><img src={hero} width={1920} height={1088} alt="Students walking through Northstar's modern academic courtyard" className="absolute inset-0 size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-primary via-primary/85 to-primary/10" /><div className="site-container relative flex min-h-[680px] items-center py-20"><div className="max-w-3xl"><p className="eyebrow text-accent">Higher education, rethought</p><h1 className="mt-6 font-display text-6xl font-semibold leading-[0.95] text-primary-foreground md:text-8xl">Learn with purpose.<br />Lead what’s next.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-primary-foreground/80">Rigorous programmes, expert mentors, and real-world practice for people ready to make meaningful progress.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" variant="accent"><Link to="/programs">Explore programmes <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/40 bg-primary/20 text-primary-foreground hover:bg-primary-foreground hover:text-primary"><Link to="/admissions">Admissions 2026</Link></Button></div></div></div>
  </section>
  <section className="border-b border-border bg-background"><div className="site-container grid grid-cols-2 divide-x divide-border md:grid-cols-4">{[["24+","Career-focused programmes"],["18:1","Student–faculty ratio"],["42","Industry partners"],["91%","Career outcome target"]].map(([value,label]) => <div key={label} className="px-4 py-8 first:pl-0 md:py-10"><strong className="block font-display text-4xl text-primary">{value}</strong><span className="mt-2 block text-xs font-bold uppercase text-muted-foreground">{label}</span></div>)}</div></section>
  <section className="py-24"><div className="site-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="Featured programmes" title="Build depth. Create momentum." copy="Learn through demanding coursework, collaborative studios, and industry-connected projects." /><Button asChild variant="outline"><Link to="/programs">View all programmes <ArrowRight /></Link></Button></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{programs.slice(0,3).map(p => <ProgramCard key={p.slug} program={p} />)}</div></div></section>
  <section className="bg-secondary py-24"><div className="site-container"><SectionHeading eyebrow="The Northstar difference" title="An education designed around doing." /><div className="mt-12 grid gap-px bg-border md:grid-cols-3">{[[Lightbulb,"Interdisciplinary by design","Connect business, design, technology, and society instead of learning in silos."],[BriefcaseBusiness,"Practice from day one","Work on live briefs, simulations, and field projects with experienced practitioners."],[Globe2,"Global, grounded outlook","Develop the perspective and judgement to act responsibly across cultures and contexts."]].map(([Icon,title,copy]) => { const C = Icon as typeof Lightbulb; return <article key={title as string} className="bg-background p-8"><C className="size-8 text-accent" /><h3 className="mt-8 font-display text-2xl font-semibold">{title as string}</h3><p className="mt-3 leading-7 text-muted-foreground">{copy as string}</p></article>})}</div></div></section>
  <section className="py-24"><div className="site-container grid items-center gap-12 lg:grid-cols-2"><div className="relative"><img src={studio} loading="lazy" width={1408} height={1008} alt="Students collaborating with a faculty mentor in the learning studio" className="aspect-[4/3] w-full object-cover" /><div className="absolute -bottom-6 right-0 bg-accent p-6 md:right-8"><strong className="font-display text-3xl">60%</strong><p className="max-w-44 text-sm font-semibold">of learning is project-led or practice-based</p></div></div><div className="lg:pl-8"><SectionHeading eyebrow="Learning experience" title="Small cohorts. Big questions. Real stakes." copy="Our learning model combines close faculty access with ambitious, team-based work. You will test ideas, receive precise feedback, and build a body of work that demonstrates what you can do." /><Button asChild variant="link" className="mt-6 px-0"><Link to="/campus-life">Explore the experience <ArrowRight /></Link></Button></div></div></section>
  <section className="bg-primary py-24"><div className="site-container"><SectionHeading eyebrow="Meet your mentors" title="Scholars who stay close to practice." copy="Our faculty bring research depth, industry judgement, and a genuine commitment to each learner." light /><div className="mt-12 grid gap-5 md:grid-cols-3">{faculty.slice(0,3).map(f => <article key={f.name} className="border border-primary-foreground/15 p-7 text-primary-foreground"><span className="grid size-16 place-items-center rounded-full bg-accent font-display text-xl font-bold text-accent-foreground">{f.initials}</span><h3 className="mt-8 font-display text-2xl font-semibold">{f.name}</h3><p className="mt-2 text-sm text-primary-foreground/60">{f.role}</p><p className="mt-5 text-xs font-bold uppercase text-accent">{f.expertise.join(" · ")}</p></article>)}</div><Button asChild variant="link" className="mt-8 px-0 text-accent"><Link to="/faculty">Meet the faculty <ArrowRight /></Link></Button></div></section>
  <section className="py-24"><div className="site-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Student perspective" title="What rigorous support feels like." /><blockquote className="border-l-4 border-accent pl-8"><Quote className="size-9 text-primary" /><p className="mt-6 font-display text-3xl leading-snug text-foreground md:text-4xl">“I wasn’t only taught frameworks. I learned to ask better questions, defend my decisions, and make work that mattered beyond the classroom.”</p><footer className="mt-6 text-sm font-bold">Maya R. — MSc Applied Data Science</footer></blockquote></div></section>
  <section className="bg-secondary py-24"><div className="site-container"><div className="flex justify-between gap-5"><SectionHeading eyebrow="On campus" title="Ideas, events, and new perspectives." /><Button asChild variant="outline" className="hidden md:inline-flex"><Link to="/events">All events & news</Link></Button></div><div className="mt-12 grid gap-5 md:grid-cols-2">{stories.slice(0,2).map(s => <article key={s.slug} className="bg-background p-7"><p className="eyebrow text-primary">{s.type} · {s.category}</p><h3 className="mt-5 font-display text-3xl font-semibold">{s.title}</h3><p className="mt-4 leading-7 text-muted-foreground">{s.excerpt}</p><p className="mt-6 text-xs font-bold uppercase text-muted-foreground">{s.date}</p><Button asChild variant="link" className="mt-3 px-0"><Link to="/events/$slug" params={{slug:s.slug}}>Read more <ArrowRight /></Link></Button></article>)}</div></div></section>
  <AdmissionsBand />
</> }