import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { programs } from "@/lib/content";
import { PageIntro, ProgramCard } from "@/components/shared";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/programs")({ head: () => ({ meta: [{ title: "Programmes — Northstar Institute" }, { name: "description", content: "Explore Northstar undergraduate, postgraduate, diploma, and certification programmes." }, { property: "og:title", content: "Programmes — Northstar Institute" }, { property: "og:description", content: "Find a rigorous programme designed around your next step." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProgramsPage });
function ProgramsPage(){ const [q,setQ]=useState(""); const [category,setCategory]=useState("All"); const [mode,setMode]=useState("All"); const [sort,setSort]=useState("featured"); const shown=useMemo(()=>programs.filter(p=>(category==="All"||p.category===category)&&(mode==="All"||p.mode===mode)&&`${p.title} ${p.description} ${p.school}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="az"?a.title.localeCompare(b.title):sort==="duration"?parseInt(a.duration)-parseInt(b.duration):0),[q,category,mode,sort]); return <><PageIntro eyebrow="Academic programmes" title="Find the path that moves you forward." description="Browse programmes built around strong foundations, applied practice, and the skills employers and communities need next."/><section className="py-16"><div className="site-container"><div className="grid gap-4 border-b border-border pb-8 lg:grid-cols-[1fr_auto_auto_auto]"><div className="relative"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Search programmes" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by subject or school" className="h-11 pl-12"/></div><select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)} className="h-11 border border-input bg-background px-4 text-sm">{["All","Undergraduate","Postgraduate","Diploma","Certification"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by mode" value={mode} onChange={e=>setMode(e.target.value)} className="h-11 border border-input bg-background px-4 text-sm">{["All","On campus","Hybrid","Online"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort programmes" value={sort} onChange={e=>setSort(e.target.value)} className="h-11 border border-input bg-background px-4 text-sm"><option value="featured">Featured</option><option value="az">A–Z</option><option value="duration">Shortest duration</option></select></div><div className="mt-8 flex items-center gap-2 text-sm text-muted-foreground"><SlidersHorizontal className="size-4"/>{shown.length} programmes</div>{shown.length?<div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map(p=><ProgramCard key={p.slug} program={p}/>)}</div>:<div className="my-16 border border-dashed border-border bg-muted p-12 text-center"><h2 className="font-display text-3xl font-semibold">No programmes match</h2><p className="mt-3 text-muted-foreground">Try clearing a filter or using a broader search.</p><Button className="mt-6" onClick={()=>{setQ("");setCategory("All");setMode("All")}}>Clear filters</Button></div>}</div></section></> }